version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "develop"
    assignees:
      - "Yousha"
    versioning-strategy: "increase"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    target-branch: "main"
    assignees:
      - "Yousha"
    versioning-strategy: "increase"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    target-branch: "main-php7.4"
    assignees:
      - "Yousha"
    versioning-strategy: "increase"
